// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    sidebar: [
        { type: "autogenerated", dirName: "." },
        { type: "link", label: "Changelog", href: "/sqlpay/changelog" },
    ],
};

export default sidebars;
